[rule_configuration]
webview_pre_execute = ''
common_track_args = [
]

[[rules]]
regex = '^(https:\/\/)?(twitter|x)\.com\/[a-zA-Z0-9\-_.]+\/status\/\d+'
action = 'WEB_VIEW'
javascript = '''
document.onUrlPreLoad = (url) => {
    var previewFixupUrl = originalUrl
        .replace('//twitter.com', '//vxtwitter.com')
        .replace('//x.com', '//vxtwitter.com');
       console.log(previewFixupUrl);
    control.completion(
        control.cleanUrlParams(previewFixupUrl, ['p'], false)
    );
}
'''
