[rule_configuration]
webview_pre_execute = ''
common_track_args = [
]

[[rules]]
regex = 'https:\/\/(x|twitter)\.com\/[a-zA-Z0-9\-_.]+\/status\/\d+'
action = 'WEB_VIEW'
javascript = '''
document.onUrlPreLoad = (url) => {
    const previewFixupUrl = originalUrl.replaceAll('x.com', 'vxtwitter.com').replaceAll('twitter.com', 'vxtwitter.com');
    return;
    control.completion(
        control.cleanUrlParams(previewFixupUrl, ['p'], false)
    );
}
'''
